spring:
  application:
    name: metadata

  datasource:
    url: jdbc:mysql://localhost:3306/metadata?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8010
