spring:
  application:
    name: metadata
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active:
      - "prod"

  datasource:
    url: jdbc:mysql://localhost:3306/metadata?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

server:
  port: 8010

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    shutdown:
      access: unrestricted # Allow gracefully shutdown of the microservice
  info:
    env:
      enabled: true # Enable display of the microservice info in the actuator endpoints
eureka:
  instance:
    preferIpAddress: true # prefer the IP address the client registered with
  client:
    fetchRegistry: true # fetch registry details of other microservices
    registerWithEureka: true # Tells Eureka to register with Itself
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

info:
  app:
    name: "metadata"
    description: "Metadata Microservice"
    version: "1.0.0"

logging:
  level:
    com:
      alienworkspace:
        cdr:
          metadata: DEBUG